#!/bin/ksh

DIR=$(dirname $(whence $0))

set -o errexit

export DESTDIR=/
export PREFIX=${DIR}/BUILD
export MAKE=/opt/local/bin/dmake

rm -rf ${DIR}/BUILD

cd $DIR/src

echo "cleaning ..."
./build clean
echo "building ..."
./build install

