
$quote "


$set	1
$
$ CDDL HEADER START
$
$ The contents of this file are subject to the terms of the
$ Common Development and Distribution License (the "License").
$ You may not use this file except in compliance with the License.
$
$ You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
$ or http://www.opensolaris.org/os/licensing.
$ See the License for the specific language governing permissions
$ and limitations under the License.
$
$ When distributing Covered Code, include this CDDL HEADER in each
$ file and include the License file at usr/src/OPENSOLARIS.LICENSE.
$ If applicable, add the following below this CDDL HEADER, with the
$ fields enclosed by brackets "[]" replaced with your own identifying
$ information: Portions Copyright [yyyy] [name of copyright owner]
$
$ CDDL HEADER END
$
$ Copyright 1996 Sun Microsystems, Inc. All rights reserved.
$ Use is subject to license terms.
$
$ @(#)libvroot.msg 1.2 06/12/12
$
142	"file_lock: file %s is already locked.\n"
143	"file_lock: will periodically check the lockfile %s for two minutes.\n"
144	"Current working directory %s\n"
145	"Could not lock file `%s'; "
146	" failed - "
147	"Couldn't write to %s"
148	"Cannot open `%s' for writing\n"
149	"Cannot open %s for writing\n"
