
$quote "


$set	1
$
$ CDDL HEADER START
$
$ The contents of this file are subject to the terms of the
$ Common Development and Distribution License (the "License").
$ You may not use this file except in compliance with the License.
$
$ You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
$ or http://www.opensolaris.org/os/licensing.
$ See the License for the specific language governing permissions
$ and limitations under the License.
$
$ When distributing Covered Code, include this CDDL HEADER in each
$ file and include the License file at usr/src/OPENSOLARIS.LICENSE.
$ If applicable, add the following below this CDDL HEADER, with the
$ fields enclosed by brackets "[]" replaced with your own identifying
$ information: Portions Copyright [yyyy] [name of copyright owner]
$
$ CDDL HEADER END
$
$ Copyright 1996 Sun Microsystems, Inc. All rights reserved.
$ Use is subject to license terms.
$
$ @(#)libmksh.msg 1.2 06/12/12
$
89	"ulimit() failed: %s"
90	"Couldn't open standard out temp file `%s': %s"
91	"Couldn't open standard error temp file `%s': %s"
92	"Could not load `/usr/bin/nice': %s"
93	"Could not load Shell from `%s': %s"
94	"fork failed: %s"
95	"Command `%s' has more than %d arguments"
96	"Cannot load command `%s': %s"
97	"fork failed: %s"
98	"wait() failed: %s"
99	"Could not open filter file for -X"
100	"Could not stat filter file for -X"
101	"\n**** Error: Directory %s Target %s:\n%s\n"
102	"**** Error: Directory %s Target %s\n"
103	"*** Error code %d"
104	"*** Error code %d"
105	"*** Signal %d"
106	"*** Signal %d"
107	" - core dumped"
108	" - core dumped"
109	" (ignored)"
110	" (ignored)"
111	"Could not run command `%ls' for :sh transformation"
112	"The command `%ls' returned status `%d'"
113	"Loop detected when expanding macro value `%ls'"
114	"'$' at end of string `%ls'"
115	"'$' at end of line"
116	"Unmatched `%lc' in string `%ls'"
117	"Premature EOF"
118	"Unmatched `%lc' on line"
119	"Illegal macro reference `%ls'"
120	"= missing from replacement macro reference"
121	"= missing from replacement macro reference"
122	"%% missing from replacement macro reference"
123	"%% missing from replacement macro reference"
124	"Too many %% in pattern"
125	"Conditional macro `%s' referenced on line %d"
126	"Out of memory"
127	"Error %d"
128	"mksh: Fatal error: "
129	"Current working directory %s\n"
131	"mksh: Fatal error in reader: "
133	"Current working directory %s\n"
134	"mksh: Warning: "
135	"Current working directory %s\n"
136	"Internal error. Unknown prop type %d"
137	"`cd %s' failed, and conversion of %s to automounter pathname also failed"
138	"`cd %s' and `cd %s' both failed"
139	"The following command caused the error:\n%s\n"
140	"Error reading `%ls': Premature EOF"
141	"Error reading `%ls': %s"
142	"newline is not last character in file %ls"
164	"Conditional macro `%ls' referenced in file `%ls', line %d"
