#!/bin/ksh

set -o errexit

function usage
{
  echo "Usage: $0 [ clean | all | install ]" >&2
}

function fatal
{
  rc=$1
  shift
  echo "$@" >&2
  exit $rc
}

if [[ $# -ne 0 ]]; then
  target=$1
else
  target="install"
fi

case "$target" in
  clean|all|install)
    ;;
  *)
    fatal 1 "Usage: $0 [ clean | all | install ]"
    ;;
esac

CC=/ws/plat/proto/usr/bin/gcc
CCC=/bin/false
CC64=/bin/false
CCC64=/bin/false

export CC CCC CC64 CCC64

if [[ -z "$PREFIX" || -z "$DESTDIR" || -z "$MAKE" ]]; then
  fatal 2 "please set PREFIX and DESTDIR and MAKE"
fi

if [[ ! -d "$DESTDIR" ]]; then
  mkdir -p "$DESTDIR"
fi


export DESTDIR=$(cd "$DESTDIR" && pwd)

cd ./make_src

# Do the build itself, using .../make_src/Makefile.

echo
echo "=== starting build ==="
echo
echo "Using variables:"
echo
echo "	 CC = $CC"
echo "	 CCC = $CCC"
echo "	 PREFIX = $PREFIX"
echo "	 DESTDIR = $DESTDIR"
echo "	 MAKE = $MAKE"
echo

$MAKE \
  CC=${CC} CCC=${CCC} \
  DESTDIR=${DESTDIR} \
  MAKE=${MAKE} \
  PREFIX=${PREFIX} \
  $target

echo
echo === build complete ===
echo
echo Binaries installed at $DESTDIR'/'$PREFIX':'
#echo
#cd $DESTDIR/$PREFIX
#find . -type f -print | sed 's/^/	/'
